var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":42,"id":120,"methods":[{"el":18,"sc":2,"sl":17},{"el":21,"sc":1,"sl":19},{"el":25,"sc":1,"sl":22},{"el":39,"sc":1,"sl":26},{"el":41,"sc":1,"sl":40}],"name":"CommonMethods","sl":14}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_0":{"methods":[{"sl":17}],"name":"loginInvalidDetails2","pass":true,"statements":[{"sl":18}]},"test_1":{"methods":[{"sl":17},{"sl":19}],"name":"clickOnLoginButton","pass":true,"statements":[{"sl":18},{"sl":20},{"sl":21}]},"test_10":{"methods":[{"sl":17},{"sl":19}],"name":"tabOnLoginwithFacebook","pass":true,"statements":[{"sl":18},{"sl":20},{"sl":21}]},"test_11":{"methods":[{"sl":17}],"name":"loginInvalidDetails11","pass":true,"statements":[{"sl":18}]},"test_12":{"methods":[{"sl":17}],"name":"loginInvalidDetails3","pass":true,"statements":[{"sl":18}]},"test_13":{"methods":[{"sl":17}],"name":"loginInvalidDetails9","pass":true,"statements":[{"sl":18}]},"test_15":{"methods":[{"sl":17}],"name":"loginInvalidDetails7","pass":true,"statements":[{"sl":18}]},"test_16":{"methods":[{"sl":17}],"name":"loginInvalidDetails10","pass":true,"statements":[{"sl":18}]},"test_2":{"methods":[{"sl":17}],"name":"loginInvalidDetails6","pass":true,"statements":[{"sl":18}]},"test_3":{"methods":[{"sl":17},{"sl":26}],"name":"Signout","pass":true,"statements":[{"sl":18},{"sl":27},{"sl":28},{"sl":29},{"sl":30},{"sl":31},{"sl":32},{"sl":33},{"sl":39}]},"test_4":{"methods":[{"sl":17}],"name":"loginInvalidDetails5","pass":true,"statements":[{"sl":18}]},"test_5":{"methods":[{"sl":17}],"name":"loginInvalidDetails4","pass":false,"statements":[{"sl":18}]},"test_6":{"methods":[{"sl":17}],"name":"loginInvalidDeatils1","pass":true,"statements":[{"sl":18}]},"test_7":{"methods":[{"sl":17}],"name":"loginInvalidDetails8","pass":true,"statements":[{"sl":18}]},"test_8":{"methods":[{"sl":17},{"sl":19}],"name":"createAnAccount","pass":false,"statements":[{"sl":18},{"sl":20},{"sl":21}]},"test_9":{"methods":[{"sl":17}],"name":"loginValidDetails","pass":true,"statements":[{"sl":18}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [1, 5, 10, 7, 15, 16, 0, 11, 6, 8, 3, 2, 12, 4, 9, 13], [1, 5, 10, 7, 15, 16, 0, 11, 6, 8, 3, 2, 12, 4, 9, 13], [1, 10, 8], [1, 10, 8], [1, 10, 8], [], [], [], [], [3], [3], [3], [3], [3], [3], [3], [3], [], [], [], [], [], [3], [], [], []]
